name: Main-production

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Push to Prod
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git remote add Production https://github.com/TehBing/CSIT314-Grp48.git
          git remote -v  # Print remotes for debugging
          git push Production main
        
