name: Main-production

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Push to Prod
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.email "chewzongyuan@yahoo.com"
          git config --global user.name "chew@1990"
          git remote add Production https://github.com/TehBing/CSIT314-Grp48.git
          git fetch origin main
          git push origin Production 
        
