name: Main-production

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Push to Prod
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git fetch origin main
          git push origin Production
        
